# GET http://localhost:5000/auth
### auth
POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "username": "user3",
    "password": "123456",
    "name":"User",
    "email":"user@gmail.com",
    "phone":"0347785468",
    "address":"An Phu Thuan An Binh Duong",
    //"shopName":"Tuan",
    "gt":"Nam",
    "dateOfBirth":"02/01/2000"
    //"role":"Admin"
}

###

POST http://localhost:5000/auth/login
Content-Type: application/json


{
    "username":"admin",
    //"username":"user",
    "password":"123456"
}

###
GET http://localhost:5000/auth
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmM1OTFiZmMwNGZkZmRlYjhlODM4NWQiLCJyb2xlIjoiQWRtaW4iLCJpYXQiOjE2NjAyMjM0OTksImV4cCI6MTY2MDIyMzc5OX0.7QgyC62k9y9BBq5zgfBSEuqhJUFRcobP8RmC3V42mD4
###

POST http://localhost:5000/auth/test
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmM1OTFiZmMwNGZkZmRlYjhlODM4NWQiLCJyb2xlIjoiQWRtaW4iLCJpYXQiOjE2NjEwMDMxNzMsImV4cCI6MTY2MTAwMzQ3M30.thi-LQtOAf6X0P1-ewIT70gU4R9cw_BE1KdzNjOMgDQ

################################

POST http://localhost:5000/auth/token
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmM1OTFiZmMwNGZkZmRlYjhlODM4NWQiLCJyb2xlIjoiQWRtaW4iLCJpYXQiOjE2NjEwMDM0MDcsImV4cCI6MTY2MTAwMzcwN30.9z4fwhsQ5qSV2sx7h6RjdqidN8rcSKvwEHFK5lUfdz4


{
    "refreshToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmM1OTFiZmMwNGZkZmRlYjhlODM4NWQiLCJyb2xlIjoiQWRtaW4iLCJpYXQiOjE2NjEwMDM0MDcsImV4cCI6MTY2MTAwNzAwN30.qjngc_Tg7tdgxeprh-C0lMKpIrXMg0-zY3fLfDpXZzY"
}

###
DELETE http://localhost:5000/auth/delete
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmM1OTFiZmMwNGZkZmRlYjhlODM4NWQiLCJyb2xlIjoiQWRtaW4iLCJpYXQiOjE2NTczNTg5NTMsImV4cCI6MTY1NzM1OTI1M30.ZZVkwfEQGhAAXknPX80PBVDSan2ufJIFEqjTqeT7GKI


### category
#get all categories
GET http://localhost:5000/category


### POST/createCategory
POST http://localhost:5000/category/createCategory
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzA4Y2JiNjFiMDllYWIzMTJhNGZkZjMiLCJyb2xlIjp0cnVlLCJpYXQiOjE2NjI3NzYyNDYsImV4cCI6MTY2Mjc3NjU0Nn0.1W58UHQhExpsKavXTb1BGCpjf5v_dWOriA3FwJTu3n4

{
    "nameCategory":"Thời trang Nam1"
}


### delete category
DELETE http://localhost:5000/category/631bf6bfeafde8547a8afcbc/delete
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzA4Y2JiNjFiMDllYWIzMTJhNGZkZjMiLCJyb2xlIjp0cnVlLCJpYXQiOjE2NjI3NzgwOTAsImV4cCI6MTY2Mjc3ODM5MH0.juUepeZwOZj7YOP6jZv5tyTI_w7jAgt2d6Leqzn36Og

### update category
PUT http://localhost:5000/category/631bf5e6eafde8547a8afca9/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzA4Y2JiNjFiMDllYWIzMTJhNGZkZjMiLCJyb2xlIjp0cnVlLCJpYXQiOjE2NjI3NzgwOTAsImV4cCI6MTY2Mjc3ODM5MH0.juUepeZwOZj7YOP6jZv5tyTI_w7jAgt2d6Leqzn36Og

{
    "nameCategory":"Quần"
}

### test upload
POST http://localhost:5000/upload


### product
POST http://localhost:5000/product/createProduct
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmM1OTFiZmMwNGZkZmRlYjhlODM4NWQiLCJyb2xlIjoiQWRtaW4iLCJpYXQiOjE2NTk1MzI0NjIsImV4cCI6MTY1OTUzMjc2Mn0.HZDc4dzj1OIiMF5oSroybHXclVcgURuIoSDSxvOk7hA

{
    "product_id":"SP006",
    "title":"Test san pham 06",
    "price":5000,
    "description":"SP Test 6",
    "content":"123456",
    "image":{"url":"https://res.cloudinary.com/tuananhgmodev/image/upload/v1657422949/cld-sample-5.jpg"},
    "category":"123456"
}

###
GET http://localhost:5000/product?limit=5

###
DELETE http://localhost:5000/product/62cad87a428c7f7f7d171d95/delete
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmM1OTFiZmMwNGZkZmRlYjhlODM4NWQiLCJyb2xlIjoiQWRtaW4iLCJpYXQiOjE2NTc0NjEwNjAsImV4cCI6MTY1NzQ2MTM2MH0.ofnk1kSrgjksMh87qLPkcraZcTFJNtVXGhS64xpIgAo

###

GET http://localhost:5000/product/detail/62dfa74163b6677e14c22d88

###
GET http://localhost:5000/cart
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzEwMGJjMjFhYmEzNmUzMTZkMDc0NWYiLCJyb2xlIjpmYWxzZSwiaWF0IjoxNjYyMDkwOTgzLCJleHAiOjE2NjIwOTEyODN9.J_8V66ZipMH_GGBpX9D_8Nx9ZxnmeYUHYmFGANciQWQ

###
PATCH  http://localhost:5000/cart/addCart
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzA4Y2UwYjFiMDllYWIzMTJhNGZlMTMiLCJyb2xlIjpmYWxzZSwiaWF0IjoxNjYyMDg3Njg4LCJleHAiOjE2NjIwODc5ODh9.R_qR81AiKVDRl9axq3DaZQVkLpZzGVUhg5GVc-bmnJ4

[
    /*
    {
        "category":"123456",
        "checked":false,
        "content":"123456",
        "description":"SP Test 2",
        "image":{"url":"https://res.cloudinary.com/tuananhgmodev/image/upload/v1657422949/cld-sample-4.jpg"},
        "price":2000,
        "product_id":"SP002",
        "sold":0,
        "title":"test san pham 02",
    "quantity":"1"
    },
     {
        "category":"123456",
        "checked":false,
        "content":"123456",
        "description":"SP Test 2",
        "image":{"url":"https://res.cloudinary.com/tuananhgmodev/image/upload/v1657422949/cld-sample-4.jpg"},
        "price":2000,
        "product_id":"SP002",
        "sold":0,
        "title":"test san pham 02",
    "quantity":"1"
    }
   */
]

###
PUT http://localhost:5000/cart/630e14d04b28c77647ddaca1/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzA4Y2JiNjFiMDllYWIzMTJhNGZkZjMiLCJyb2xlIjp0cnVlLCJpYXQiOjE2NjE4Njc3OTMsImV4cCI6MTY2MTg2ODA5M30.bXFrRjAUC16pAwB7526mVfRLk27O3UEWegBuRulrxcI

{
    
    "quantity":"5"
}

###
DELETE http://localhost:5000/cart/630e14d04b28c77647ddaca1/delete
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzA4Y2JiNjFiMDllYWIzMTJhNGZkZjMiLCJyb2xlIjp0cnVlLCJpYXQiOjE2NjE4Njc3OTMsImV4cCI6MTY2MTg2ODA5M30.bXFrRjAUC16pAwB7526mVfRLk27O3UEWegBuRulrxcI

###
POST http://localhost:5000/payment/createPayment
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzEwMGJjMjFhYmEzNmUzMTZkMDc0NWYiLCJyb2xlIjpmYWxzZSwiaWF0IjoxNjYyNTU4NjQxLCJleHAiOjE2NjI1NTg5NDF9.hIJVL4hqNwbR588JS9vqdKvX4NcEEA7x2HNPM36BRnw

{
    "paymentID":"pay001",
    "address":{"country":"VN"},
    "cart":[

        {
            "product":{

            "category":"123456",
            "checked":false,
            "content":"123456",
            "description":"SP Test 2",
            "image":{"url":"https://res.cloudinary.com/tuananhgmodev/image/upload/v1657422949/cld-sample-4.jpg"},
            "price":2000,
            "product_id":"SP002",
            "sold":0
            },
            "quantity":"1"
        },
        {
            "product":{

            "category":"123456",
            "checked":false,
            "content":"123456",
            "description":"SP Test 2",
            "image":{"url":"https://res.cloudinary.com/tuananhgmodev/image/upload/v1657422949/cld-sample-4.jpg"},
            "price":2000,
            "product_id":"SP002",
            "sold":0
            },
            "quantity":"1"
        }
        
    ],
        
       
    
    "status":true
}

###
GET http://localhost:5000/payment/history
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzEwMGJjMjFhYmEzNmUzMTZkMDc0NWYiLCJyb2xlIjpmYWxzZSwiaWF0IjoxNjYyNjQxNzQ4LCJleHAiOjE2NjI2NDIwNDh9.EQ0MrT2dQmHxz_pCGSYu0YjvFHGFTn3Zgchb9th27GU